from __future__ import annotations

import html
import logging
import re
from pathlib import Path
from typing import Any

from arcbench_agent_runtime import AgentRuntime

from .config import AgentConfig
from .llm import BudgetExhaustion, ModelBudgetExceeded, ModelClient
from .requirements import RequirementModule, load_requirement_tree, root_modules, walk_requirement_ids
from .tools import ProjectTools
from .verify import (
    CheckResult,
    VerificationResult,
    prepare_web_template_structure,
    verify_demo_page,
    verify_project,
    verify_web_template_structure,
)
from .visual_acceptance import collect_visual_references, verify_visual_acceptance


LOGGER = logging.getLogger("arcbench_agent")


def _demo_page(module: RequirementModule) -> tuple[str, str]:
    heading = module.name or module.node_id
    description = str(module.subtree.get("description") or "This page was generated by the offline ARC-Bench project demo.")
    safe_heading = html.escape(heading)
    safe_description = html.escape(description)
    page = f"""<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{safe_heading}</title>
    <style>body{{font:16px/1.6 system-ui,sans-serif;max-width:48rem;margin:10vh auto;padding:0 1.25rem;color:#172033}}main{{border:1px solid #dbe2ea;border-radius:1rem;padding:2rem}}h1{{margin-top:0}}.tag{{color:#53647a}}</style>
  </head>
  <body>
    <main>
      <p class="tag">ARC-Bench offline project demo</p>
      <h1>{safe_heading}</h1>
      <p>{safe_description}</p>
    </main>
  </body>
</html>
"""
    return page, heading


def _register_traceability(runtime: AgentRuntime, tree: dict[str, Any]) -> None:
    runtime.traceability.init_db()
    runtime.traceability.store_requirement_tree(tree)


def _record_test(runtime: AgentRuntime, node_id: str, result: VerificationResult) -> None:
    test_id = f"TEST-{node_id}"
    runtime.traceability.upsert_test(
        test_id=test_id,
        req_id=node_id,
        type="INTEGRATION",
        passed=result.passed,
    )
    runtime.traceability.set_test_pass_status(test_id, result.passed)


def _failure_signature(result: VerificationResult) -> tuple[tuple[str, int | None, tuple[str, ...]], ...]:
    """Identify repeated verification failures without volatile test timings."""
    markers = ("not ok", "error", "missing", "failed", "actual", "expected", "could not")
    return tuple(
        (
            check.name,
            check.exit_code,
            tuple(
                line.strip()
                for line in check.output.splitlines()
                if any(marker in line.casefold() for marker in markers)
            ) or (check.output[:500],),
        )
        for check in result.checks
        if not check.passed
    )


def _repair_feedback(result: VerificationResult) -> str:
    failures = [check for check in result.checks if not check.passed]
    passed = [check.name for check in result.checks if check.passed]
    parts = []
    for check in failures:
        output = check.output
        if len(output) > 4_000:
            output = output[:2_000] + "\n...[middle truncated]\n" + output[-2_000:]
        parts.append(f"{check.name}: FAILED (exit={check.exit_code})\n{output}")
    if passed:
        parts.append("Already passing checks: " + ", ".join(passed))
    return "\n\n".join(parts)


def _repair_modules(
    result: VerificationResult,
    modules: list[RequirementModule],
    module_paths: dict[str, set[str]],
) -> list[RequirementModule]:
    failure_text = "\n".join(
        f"{check.name}\n{check.output}" for check in result.checks if not check.passed
    )
    by_requirement = [
        module for module in modules
        if any(
            re.search(rf"(?<![\w.-]){re.escape(node_id)}(?![\w.-])", failure_text)
            for node_id in walk_requirement_ids(module.subtree)
        )
    ]
    if by_requirement:
        return by_requirement
    normalized = failure_text.replace("\\", "/").casefold()
    by_path = [
        module for module in modules
        if any(path.casefold() in normalized for path in module_paths.get(module.node_id, set()))
    ]
    return by_path or modules


def run_offline_demo(runtime: AgentRuntime, config: AgentConfig, tree: dict[str, Any], modules: list[RequirementModule]) -> VerificationResult:
    module = modules[0]
    node_ids = walk_requirement_ids(module.subtree)
    runtime.events.mark_design_started(module.node_id, "Offline demo planning started")
    runtime.events.mark_design_done(module.node_id, "Deterministic demo plan ready")
    runtime.events.mark_implementation_started(module.node_id, "Generating a static Web page")
    page, heading = _demo_page(module)
    config.output_dir.mkdir(parents=True, exist_ok=True)
    (config.output_dir / "index.html").write_text(page, encoding="utf-8", newline="\n")
    runtime.events.mark_implementation_done(module.node_id, "Generated index.html")
    result = verify_demo_page(config.output_dir, heading)
    for node_id in node_ids:
        if result.passed:
            runtime.events.mark_test_passed(node_id, "Offline page verification passed")
        else:
            runtime.events.mark_test_failed(node_id, result.summary())
        _record_test(runtime, node_id, result)
    _register_traceability(runtime, tree)
    return result


def run_model_agent(runtime: AgentRuntime, config: AgentConfig, tree: dict[str, Any], modules: list[RequirementModule]) -> VerificationResult:
    if config.task_type != "web":
        raise ValueError(
            f"The initial model-driven implementation currently supports task type 'web', not {config.task_type!r}"
        )
    prepare_web_template_structure(config.output_dir)
    model = ModelClient(max_turns=config.max_model_turns, max_tool_calls=config.max_tool_calls)
    project_tools = ProjectTools(config.output_dir, timeout_seconds=120)
    plans: dict[str, str] = {}
    planning_subtrees: dict[str, dict[str, Any]] = {}
    module_paths: dict[str, set[str]] = {}
    budget_failure: BudgetExhaustion | None = None
    budget_exhausted = False
    visual_references = collect_visual_references(tree)

    def checkpoint_feedback() -> str:
        checks = (
            *verify_project(config.output_dir).checks,
            *verify_web_template_structure(config.output_dir).checks,
        )
        failures = [check for check in checks if not check.passed]
        if not failures:
            LOGGER.info("Implementation checkpoint: current build and test scripts passed")
            return "Current build and test scripts pass. Finish any uncovered requirements and run final checks."
        LOGGER.warning("Implementation checkpoint found %d failing checks", len(failures))
        return "\n\n".join(
            f"{check.name}: FAILED (exit={check.exit_code})\n{check.output[-6000:]}"
            for check in failures
        )

    root_visual_references = tree.get("visual_reference", [])
    if isinstance(root_visual_references, str):
        root_visual_references = [root_visual_references]
    for module in modules:
        runtime.events.mark_design_started(module.node_id, "Analyzing requirement subtree")
        planning_subtree = dict(module.subtree)
        module_visual_references = planning_subtree.get("visual_reference", [])
        if isinstance(module_visual_references, str):
            module_visual_references = [module_visual_references]
        if isinstance(root_visual_references, list):
            planning_subtree["visual_reference"] = list(
                dict.fromkeys([*root_visual_references, *module_visual_references])
            )
        planning_subtrees[module.node_id] = planning_subtree
        try:
            plan = model.plan(
                config.task_type,
                planning_subtree,
                reference_dir=config.requirement_dir,
            )
        except ModelBudgetExceeded as exc:
            budget_exhausted = True
            budget_failure = exc.report
            LOGGER.warning("%s; preserving current files for verification", exc)
            break
        plans[module.node_id] = plan
        runtime.events.mark_design_done(module.node_id, "Implementation plan prepared")
        runtime.events.mark_implementation_started(module.node_id, "Applying requirement subtree")
        writes_before = len(project_tools.written_paths)
        budget_exhausted = model.implement(
            task_type=config.task_type,
            subtree=planning_subtree,
            plan=plan,
            project_tools=project_tools,
            reference_dir=config.requirement_dir,
            checkpoint_feedback=checkpoint_feedback,
        )
        if budget_exhausted:
            budget_exhausted = True
            candidate_report = getattr(model, "last_budget_report", None)
            budget_failure = candidate_report if isinstance(candidate_report, BudgetExhaustion) else None
            message = (
                budget_failure.summary()
                if budget_failure is not None
                else "Model implementation budget exhausted before completion"
            )
            LOGGER.warning(
                "%s; stopping further requirement generation and preserving current files for verification",
                message,
            )
            break
        if len(project_tools.written_paths) == writes_before:
            raise RuntimeError(f"No project files were changed for requirement {module.node_id}")
        module_paths.setdefault(module.node_id, set()).update(project_tools.written_paths[writes_before:])
        message = (
            "No file changes in recent tool turns; local scripts passed, continuing to the next requirement"
            if getattr(model, "last_implementation_handoff", False)
            else "Implementation turn completed"
        )
        runtime.events.mark_implementation_done(module.node_id, message)

    def verify_current_project(*, include_visual: bool = True) -> VerificationResult:
        project_result = verify_project(config.output_dir)
        structure_result = verify_web_template_structure(config.output_dir)
        visual_result = (
            verify_visual_acceptance(
                config.output_dir,
                config.requirement_dir,
                visual_references,
                model,
            )
            if visual_references and include_visual and project_result.passed and structure_result.passed
            else None
        )
        checks = (*project_result.checks, *structure_result.checks)
        if visual_result is not None:
            checks = (*checks, *visual_result.checks)
        return VerificationResult(
            project_result.passed
            and structure_result.passed
            and (visual_result is None or visual_result.passed),
            checks,
        )

    result = verify_current_project(include_visual=not budget_exhausted)
    if isinstance(getattr(model, "last_budget_report", None), BudgetExhaustion):
        budget_exhausted = True
        budget_failure = model.last_budget_report
    seen_failures: set[tuple[tuple[str, int | None, tuple[str, ...]], ...]] = set()
    while not result.passed and not budget_exhausted:
        signature = _failure_signature(result)
        if signature in seen_failures:
            LOGGER.warning("Verification failures did not change after repair; stopping repeated attempts")
            break
        seen_failures.add(signature)
        feedback = _repair_feedback(result)
        repair_modules = _repair_modules(result, modules, module_paths)
        LOGGER.warning("Verification failed; repairing %d of %d requirement modules", len(repair_modules), len(modules))
        for module in repair_modules:
            writes_before = len(project_tools.written_paths)
            repair_budget_exhausted = model.implement(
                task_type=config.task_type,
                subtree=planning_subtrees[module.node_id],
                plan=plans[module.node_id],
                project_tools=project_tools,
                repair_feedback=feedback,
                reference_dir=config.requirement_dir,
            )
            module_paths.setdefault(module.node_id, set()).update(project_tools.written_paths[writes_before:])
            if repair_budget_exhausted:
                budget_exhausted = True
                candidate_report = getattr(model, "last_budget_report", None)
                budget_failure = candidate_report if isinstance(candidate_report, BudgetExhaustion) else None
                message = (
                    budget_failure.summary()
                    if budget_failure is not None
                    else "Model repair budget exhausted before completion"
                )
                LOGGER.warning(
                    "%s; stopping further repair calls",
                    message,
                )
                break
        result = verify_current_project(include_visual=not budget_exhausted)
        if isinstance(getattr(model, "last_budget_report", None), BudgetExhaustion):
            budget_exhausted = True
            budget_failure = model.last_budget_report

    if budget_exhausted:
        budget_check = CheckResult(
            "agent generation budget",
            False,
            1,
            (budget_failure.summary() if budget_failure is not None else "Model implementation budget exhausted.")
            + "\nPartial project files were preserved and the available project checks were run.",
        )
        result = VerificationResult(False, (*result.checks, budget_check))

    for node_id in walk_requirement_ids(tree):
        if node_id == "ROOT":
            continue
        if result.passed:
            runtime.events.mark_test_passed(node_id, "Project verification passed")
        else:
            runtime.events.mark_test_failed(node_id, result.summary())
        _record_test(runtime, node_id, result)
    _register_traceability(runtime, tree)
    log_usage = getattr(model, "log_usage", None)
    if callable(log_usage):
        log_usage()
    return result


def run_agent(runtime: AgentRuntime, config: AgentConfig) -> int:
    runtime.events.mark_run_started("ARC-Bench software engineering agent started")
    tree = load_requirement_tree(config.requirement_dir)
    modules = root_modules(tree)
    config.output_dir.mkdir(parents=True, exist_ok=True)
    _register_traceability(runtime, tree)
    if config.demo_mode:
        result = run_offline_demo(runtime, config, tree, modules)
    else:
        result = run_model_agent(runtime, config, tree, modules)
    if result.passed:
        runtime.events.mark_run_completed("Agent finished and verification passed")
        LOGGER.info("Agent completed successfully")
        return 0
    runtime.events.mark_run_failed("Agent finished but verification did not pass")
    LOGGER.error("Verification failed:\n%s", result.summary())
    return 1
