from __future__ import annotations

import html
import logging
from pathlib import Path
from typing import Any

from arcbench_agent_runtime import AgentRuntime

from .config import AgentConfig
from .llm import ModelClient
from .requirements import RequirementModule, load_requirement_tree, root_modules, walk_requirement_ids
from .tools import ProjectTools
from .verify import VerificationResult, verify_demo_page, verify_project


LOGGER = logging.getLogger("arcbench_agent")


def _demo_page(module: RequirementModule) -> tuple[str, str]:
    heading = module.name or module.node_id
    description = str(module.subtree.get("description") or "This page was generated by the offline ARC-Bench project demo.")
    safe_heading = html.escape(heading)
    safe_description = html.escape(description)
    page = f"""<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{safe_heading}</title>
    <style>body{{font:16px/1.6 system-ui,sans-serif;max-width:48rem;margin:10vh auto;padding:0 1.25rem;color:#172033}}main{{border:1px solid #dbe2ea;border-radius:1rem;padding:2rem}}h1{{margin-top:0}}.tag{{color:#53647a}}</style>
  </head>
  <body>
    <main>
      <p class="tag">ARC-Bench offline project demo</p>
      <h1>{safe_heading}</h1>
      <p>{safe_description}</p>
    </main>
  </body>
</html>
"""
    return page, heading


def _register_traceability(runtime: AgentRuntime, tree: dict[str, Any]) -> None:
    runtime.traceability.init_db()
    runtime.traceability.store_requirement_tree(tree)


def _record_test(runtime: AgentRuntime, node_id: str, result: VerificationResult) -> None:
    test_id = f"TEST-{node_id}"
    runtime.traceability.upsert_test(
        test_id=test_id,
        req_id=node_id,
        type="INTEGRATION",
        passed=result.passed,
    )
    runtime.traceability.set_test_pass_status(test_id, result.passed)


def run_offline_demo(runtime: AgentRuntime, config: AgentConfig, tree: dict[str, Any], modules: list[RequirementModule]) -> VerificationResult:
    module = modules[0]
    node_ids = walk_requirement_ids(module.subtree)
    runtime.events.mark_design_started(module.node_id, "Offline demo planning started")
    runtime.events.mark_design_done(module.node_id, "Deterministic demo plan ready")
    runtime.events.mark_implementation_started(module.node_id, "Generating a static Web page")
    page, heading = _demo_page(module)
    config.output_dir.mkdir(parents=True, exist_ok=True)
    (config.output_dir / "index.html").write_text(page, encoding="utf-8", newline="\n")
    runtime.events.mark_implementation_done(module.node_id, "Generated index.html")
    result = verify_demo_page(config.output_dir, heading)
    for node_id in node_ids:
        if result.passed:
            runtime.events.mark_test_passed(node_id, "Offline page verification passed")
        else:
            runtime.events.mark_test_failed(node_id, result.summary())
        _record_test(runtime, node_id, result)
    _register_traceability(runtime, tree)
    return result


def run_model_agent(runtime: AgentRuntime, config: AgentConfig, tree: dict[str, Any], modules: list[RequirementModule]) -> VerificationResult:
    if config.task_type != "web":
        raise ValueError(
            f"The initial model-driven implementation currently supports task type 'web', not {config.task_type!r}"
        )
    model = ModelClient(max_turns=config.max_model_turns, max_tool_calls=config.max_tool_calls)
    project_tools = ProjectTools(config.output_dir, timeout_seconds=120)
    plans: dict[str, str] = {}
    for module in modules:
        runtime.events.mark_design_started(module.node_id, "Analyzing requirement subtree")
        plan = model.plan(config.task_type, module.subtree)
        plans[module.node_id] = plan
        runtime.events.mark_design_done(module.node_id, "Implementation plan prepared")
        runtime.events.mark_implementation_started(module.node_id, "Applying requirement subtree")
        writes_before = len(project_tools.written_paths)
        model.implement(
            task_type=config.task_type,
            subtree=module.subtree,
            plan=plan,
            project_tools=project_tools,
        )
        if len(project_tools.written_paths) == writes_before:
            raise RuntimeError(f"No project files were changed for requirement {module.node_id}")
        runtime.events.mark_implementation_done(module.node_id, "Implementation turn completed")

    result = verify_project(config.output_dir)
    if not result.passed:
        feedback = result.summary()
        LOGGER.warning("Initial verification failed; starting one bounded repair pass")
        for module in modules:
            model.implement(
                task_type=config.task_type,
                subtree=module.subtree,
                plan=plans[module.node_id],
                project_tools=project_tools,
                repair_feedback=feedback,
            )
        result = verify_project(config.output_dir)

    for node_id in walk_requirement_ids(tree):
        if node_id == "ROOT":
            continue
        if result.passed:
            runtime.events.mark_test_passed(node_id, "Project verification passed")
        else:
            runtime.events.mark_test_failed(node_id, result.summary())
        _record_test(runtime, node_id, result)
    _register_traceability(runtime, tree)
    return result


def run_agent(runtime: AgentRuntime, config: AgentConfig) -> int:
    runtime.events.mark_run_started("ARC-Bench software engineering agent started")
    tree = load_requirement_tree(config.requirement_dir)
    modules = root_modules(tree)
    config.output_dir.mkdir(parents=True, exist_ok=True)
    _register_traceability(runtime, tree)
    if config.demo_mode:
        result = run_offline_demo(runtime, config, tree, modules)
    else:
        result = run_model_agent(runtime, config, tree, modules)
    if result.passed:
        runtime.events.mark_run_completed("Agent finished and verification passed")
        LOGGER.info("Agent completed successfully")
        return 0
    runtime.events.mark_run_failed("Agent finished but verification did not pass")
    LOGGER.error("Verification failed:\n%s", result.summary())
    return 1
